:jbake-title: Introduction and Goals
:jbake-type: page_toc
:jbake-status: published
:jbake-menu: arc42
:jbake-order: 1
:filename: /chapters/01_introduction_and_goals.adoc
ifndef::imagesdir[:imagesdir: ../../images]

:toc:



[[section-introduction-and-goals]]
== Introduction and Goals


=== Requirements Overview

==== What is Wasale?

Wasale is a Food delivery platforms can help restaurants expand their customer base and increase their revenue by reaching customers who prefer to dine at home.Also, it offers customers the convenience of ordering meals from a wide range of restaurants without the need to leave their homes. 

One of the key features of the Wasale system is its dynamic restaurant management capability. System administrators have the authority to register and deregister restaurants based on agreements between Wasale and contracted establishments. This flexibility ensures that the system remains up-to-date and aligned with the ever-changing landscape of serviced restaurants.



==== Main Features

===== Restaurant Management
    * System administrators can add/remove restaurants to the system.
    * Restaurants can edit their own information, including menus, location, and description. 

===== User Registration and Profiles
    * Users can register/deregister to the system.
    * Users provide the necessary details to enable the service (name, delivery address, contact details). 

===== Ordering & Search:
    * Customers can explore the existing restaurants.
    * Customers can browse restaurants using query criteria (e.g., selecting a seafood restaurant).
    * Customers can view restaurant details (menu, location, and description). 
    * Customers can place orders online.

===== Order Management:
    * Restaurants receive orders on order screens and begin preparation.
    * Restaurants can change the order status (submitted, received by the restaurant).
    * Couriers/drivers deliver orders and update the order status to "on the way."
    * Customers can track orders and optionally register for order notifications.

===== Administrator Tools
    * System administrators can search for orders based on restaurant name and order status.

<<<
=== Quality Goals


[options="header",cols="1,2,2"]
|===
|No.|Quality|Motivation
| 1 | Agility | It’s important to support the dynamic business changes, so that the system should consider the agility for the development process. 

It's a newly borned idea, the feedback from the system's users and business owner shall bring many changes to the system.

| 2 | Elasticity | The system should support the big number of customers that might order food on the peak time.

| 3 | Scalability | It’s first phase at the capital with high expectation for success and would be extended to different areas in the country. 

The system should support [10 restaurants, 1000 customers, 300 orders/day] at the first phase, expecting to increase the system capacity to accept [60 restaurants, 10,000 customers, 4000 orders/day] after 6 months.


|===

=== Stakeholders

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| Developers | - | Build a highly scalable food delivery platform with Spring Boot, Laravel and ASP.NET core.
| Wasale (Delivery Company) | - | Seeks to expand their service offerings with a robust food delivery system, providing customers with access to a wide variety of restaurants.
| Restaurants | - | Gain increased visibility and potential for more orders by partnering with the "Wasale" platform.
| Customers | - | Desire a convenient and user-friendly way to order food from their favorite local restaurants.
| Couriers | - | Seek flexible work opportunities and a reliable platform to complete delivery orders efficiently.
|===
